baseurl: ""
url: "www.paulsportfolio.tk"

theme_settings:
  title: Paul Hurrle
  description: "A Jekyll-based portfolio and blog website"

  header_text: >
     <h1>The <span style="color: Green">Green</span> Software Developer</h1>
     <p>I'm a passionate developer with experience in JavaScript, AngularJS, and Rails.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: "paul_hurrle@yahoo.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "paulhurrle"
  google_plus:
  instagram:
  linkedin:  https://www.linkedin.com/in/paulhurrle/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  https://stackexchange.com/users/11096429/paul-hurrle
  steam:
  tumblr:
  twitter: "PaulHurrle"
  wordpress:
  youtube:

  google_analytics: "UA-105072030-1"
  disqus_shortname:
  katex: true

  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

paginate: 100
paginate_path: "blog/page:num"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
